version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./ops/init.database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: thumbnailer
      MYSQL_USER: thumbnailer
      MYSQL_PASSWORD: pass!@
      MYSQL_RANDOM_ROOT_PASSWORD: true