service:
  id: thumbnailer

server:
  port: 8080
  ping: /ping

monitor:
  port: 9090
  path: /metrics

sqldb:
  # dsn: file::memory:?cache=shared
  dsn: thumbnailer.db
  batchSize: 100

log:
  level: debug
  path: ./logs/thumbnailer.log
  maxSize: 100
  maxBackups: 10
  maxAge: 30
