# db:
#   driver: mysql
#   host: localhost
#   port: 3306
#   name: thumbnailer
#   user: thumbnailer
#   password: pass!@
#   charset: utf8mb4
#   timeZone: Local
profile: local
service:
  port: 8080
monitor:
  port: 8081
  path: metrics
db:
    driver: sqlite3
    name: thumbnailer
log:
  level: debug
  path: ./logs/app.log
  maxSize: 100
  maxBackups: 10
  maxAge: 30

