# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: test
      run: go test -v ./...

  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      COVERAGE: 0.0%
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: coverage
      run: |
        go test -coverprofile=coverage.out -count=1 ./... 
        TOKENS="$(go tool cover -func=coverage.out | tail -n 1 | awk '{print $3}')"
        echo "COVERAGE=$(echo ${TOKENS})" >> $GITHUB_ENV

    - name: upload coverage badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_COVERAGE_SECRET }}
        gistID: cb32648fb86009af712ddf269c3a49c8
        filename: thumbnailer-coverage-badge.json
        label: coverage
        message: ${{ env.COVERAGE }}
        namedLogo: go
        valColorRange: ${{ env.COVERAGE }}
        minColorRange: 0
        maxColorRange: 90
